### ISSUE TITLE
docker printing out incorrect frontend port

### ISSUE THREAD

**Issue by kangarang** [ConsenSys/panvala#3]
<img width="520" alt="ss- 2019-03-08 at 6 06 35 PM" src="https://user-images.githubusercontent.com/18040654/54061025-fcaf6e00-41cc-11e9-8936-65a8cec73c62.png">

should be `Ready on http://localhost:3001`

**Comment by akuanti** [comment]
I think this is correct. That is the port inside the container, which can be different from the one exposed to the host. In the `doecker-compose.yml` we expose it on port `3001`.
