### ISSUE TITLE
Hashes on front page are always the same

### ISSUE THREAD

**Issue by hjorthjort** [ConsenSys/panvala#40]
On the front page <http://app.panvala.com/>, every slate card has a hash at the bottom, which seems to be the metadata hash (though looking at a slate, e.g., <http://app.panvala.com/slates/0>, the UI suggest the hash is of the e-mail of the proposer). In the slate views, these hashes differ, but in the main view, it displays the same hash for all slates, it seems.

[Main view](http://app.panvala.com/)
![Screenshot_2019-04-24 Panvala](https://user-images.githubusercontent.com/8545447/56636225-63e38d80-6668-11e9-8e38-506161bec156.png)

[Slate 0](http://app.panvala.com/slates/0)
![Screenshot_2019-04-24 Panvala(2)](https://user-images.githubusercontent.com/8545447/56636223-63e38d80-6668-11e9-99cc-7303c3df16cf.png)

[Slate 1](http://app.panvala.com/slates/1)
![Screenshot_2019-04-24 Panvala(3)](https://user-images.githubusercontent.com/8545447/56636349-c046ad00-6668-11e9-98fd-dfc188d73e24.png)

**Comment by hjorthjort** [comment]
On closer inspection, I find that the hash of slate 0, the same as the ones displayed at the front page, is the address of my Rinkeby test account. This seems like odd behavior.

**Comment by akuanti** [comment]
Hi @hjorthjort thanks for reporting this. It seems like the recommender information isn't getting populated properly. I'll look into it.

**Comment by akuanti** [comment]
Fixed in https://github.com/ConsenSys/panvala/pull/42
