### ISSUE TITLE
The staking interface is dead/non-responsive

### ISSUE THREAD

**Issue by hjorthjort** [ConsenSys/panvala#41]
<http://app.panvala.com/slates/stake>

Neither the 'Back' button or the 'Confirm and deposit' button do anything when I click them. I'm looking for changed DOM elements, events in the console or network events, but can't find anything. No event gets queued in MetaMask, either.

**Comment by kangarang** [comment]
fixed: 129342678417ba4e23b0f2c7d9b67f9d5ec0f2fe
