### ISSUE TITLE
api: change datatypes from STRING -> TEXT

### ISSUE THREAD

**Issue by kangarang** [ConsenSys/panvala#8]
strings have a 255 character limit

http://docs.sequelizejs.com/manual/tutorial/models-definition.html#data-types

we should change these fields to TEXT so we can accept values with > 255 characters
- `projectPlan`
- `projectTimeline`
- `teamBackgrounds`

**Comment by akuanti** [comment]
Addressed by https://github.com/ConsenSys/panvala/pull/11
