### ISSUE TITLE
Event changes

### ISSUE THREAD

**Issue by kangarang** [ConsenSys/panvala#91]
## Gatekeeper

1. `SlateCreated(uint slateID, address indexed recommender, bytes metadataHash);`
- [x] add: `uint[] requestIDs`
**ADD PLEASE (cheap!)**

2. `ConfidenceVoteFailed(uint indexed ballotID, address resource)`
- [x] add: `uint[] slateIDs`
**EXTRANEOUS. we can use `contestSlates(ballotID, resource)`**
- [ ] **ADD: `uint winnerVotes`, `uint runnerUpVotes`, `uint confidenceVoteWinner`, `uint confidenceVoteRunnerUp`**

3. `ConfidenceVoteFinalized(uint indexed ballotID, address indexed resource, uint winningSlate)`
- [x] add: `uint[] slateIDs, address staker, address recommender`
**EXTRANEOUS. we can use `contestSlates(ballotID, resource)`**

4. `RunoffFinalized(uint indexed ballotID, address indexed resource, uint winningSlate)`
- [x] add: `uint[] slateIDs, address staker, address recommender`
**EXTRANEOUS. we can use `contestSlates(ballotID, resource)`**

5. `BallotCommitted(uint indexed ballotID, address indexed voter, uint numTokens, bytes32 commitHash);`
- [x] add: `address committer` (`msg.sender`)
**ADD PLEASE**

6. `ConfidenceVoteCounted(
    uint indexed ballotID,
    address indexed resource,
    uint winningSlate,
    uint votes,
    uint totalVotes
);`
- [x] change: `votes` -> `winnerVotes`
**MAKES SENSE**
- [ ] add: `uint runnerUpSlate, uint runnerUpVotes, uint stakedSlates` (`stakedSlates` = `contest.stakedSlates.length`)
**LEANING TOWARD: remove this event, adding these values to the other voting events**

7. `RunoffStarted(uint indexed ballotID, address indexed resource, uint winningSlate, uint runnerUpSlate)`
- [ ] change: `winningSlate` -> `leadingSlate`
**EXTRANEOUS. this data should be a part of `ConfidenceVoteFailed`**

8. - [ ] add: `SlateRejected(uint ballotID, address resource, uint slateID)`
**ADD MAYBE: if we add this, maybe it makes sense to add a `SlateAccepted` event as well**

## ParameterStore

1. `ParameterInitialized(bytes32 key, bytes32 value)`
- [ ] add: `string name`
- this would be helpful when enumerating parameters
**THIS IS GOOD. but we are going to simplify the -initialized and -set events**

## TokenCapacitor

- [x] **1. ADD: `BalancesUpdated(uint unlockedBalance, uint lastLockedBalance, uint lastLockedTime, uint balance)`** (review the arg names)

**Comment by akuanti** [comment]
@kangarang can you specify your use cases for the changes that involve adding arguments? In some cases, particularly the vote-related ones, it seems like you should be able to get the data you want from previous events in the flow.

I would also like to change all occurrences in the contracts of `ballotID` to `epochNumber`, because it's kind of confusing to have two names for the same thing.
